const ANSWER_DICT = {
  ocultar: `Aver, tarado..No tiene ningún sentido que el gobierno o una “elite” oculte que la tierra es plana, por que este concepto fue refutado hace 2500 años por muchos pensadores que no eran parte de ningún gobierno ni logia, ejemplo de ello son:
  Anaximandro de Samos (S.VI AC.) demostró la redondez de la Tierra,Eratóstenes (S.III AC) calculó la longitud del meridiano terrestre en unos 39.700 Kms. y teniendo en cuenta que la primer logia, los masones son del año 1717 no hay quien quiera manipular nada, en la época de Eratóstenes el gobierno era inestable y los romanos todavía no tenían poder allí.
  solo eres un estupido que no sabe nada y te comes los mocos, revisa la historia y contexto histórico para “despertar”...te están cagando y no te das cuenta, no seas boludo.
  `,
  domo: "Que? como que domo?, que estupidez es esa? no existe ninguna evidencia de la existencia de un domo, pues no se ve ningún reflejo, si fuera algo sólido como para evitar que algo entre o salga, debería ensuciarse, más con una teoría que habla de un mar por sobre ese domo, si o si debería estar sucio, viste a alguien limpiando el domo?..si nada entra como es que entran los meteoritos?...pues lo hacen porque no existe, por eso mandamos sondas al espacio, y que lógica tiene que en una tierra plana exista una cúpula esférica? tan solo es una idea loca de alguien que no tiene pruebas y solo se las cuela a los idiotas como tu.",
  luna: "La llegada del hombre a la luna es el tema por el cual seguro entraste en el mundo conspiranoico,lo que no sabes es que la carrera espacial era para mostrar poder entre EEUU y Rusia,los rusos pusieron al primer hombre en órbita y los Americanos querian ir un paso más allá,el punto es en el lanzamiento del apolo 1 incineraron a 3 astronautas y fue un desastre,de allí decidieron hacer lo más lógico,misiones no tripuladas hasta el apolo 7, que orbitó la tierra, luego apolo 8 logró llegar a la órbita lunar, apolo 9 probaron el módulo lunar pero no podían arriesgarse a alunizar,apolo 10 la más triste ya que probaron el equipo para combinar las 2 misiones anteriores, tan cerca pero sin tener orden de alunizar y recién en el apolo 11 se da el alunizaje, con un discurso listo por si los astronautas morían, fue que se dio el alunizaje. El detalle del discurso es algo que se supo y que no tendría sentido en un montaje, ese detalle no habría existido. Existen muchas “pruebas de la falsedad de las fotos”, así como pruebas de que son reales, tú te posicionas donde quieras, pero recuerda que se hicieron muchísimos lanzamientos innecesarios en un escenario de montaje que no tendría sentido hacer, hay objetos visibles y utilizables que demuestran que las cosas están allí, y 6 misiones exitosas más, con lo cual tienes 12 astronautas que pisaron la luna,6 orbitando esas misiones y 12 que participaron previo al alunizaje,en un total de 30 personas que estaban en el espacio para dicha misión y el más disidente fue Buzz Aldrin que lejos de negar el alunizaje habló de extraterrestres. lo cual no tiene nada que ver si la tierra es o no plana, ni siquiera con la veracidad del alunizaje, con lo cual nos deja que es muy poco probable que sea un montaje,y solo un poco probable que Aldrin este tocado y vea cosas, pero aqui el mas tonto eres tu, que te saltas todas las pruebas y te quedas con tonterias que inventó un viejo llamado Bill Kaysing que hasta acepto que su libro era una farsa para tontos como tu.",
  gravedad:
    "La gravedad no es una fuerza, pero si una propiedad de los cuerpos, es imposible hacer pruebas en laboratorios por que toda la tierra está afectada por ella, si se hace en la estación espacial, pero como eres un desgraciado no crees en ellos.Ahora veamos, si no existe la gravedad? ¿Cómo explicas los fenómenos que suceden en la tierra? ¿Piensas que la tierra plana tiene un propulsor debajo que la acelera y así nos mantenemos pegados?...pues en un año deberíamos alcanzar la velocidad de la luz y las estrellas las veríamos como viajando en star wars, lo cual es estupido, piensas que es por densidad?.. bueno te informo que la densidad se basa sobre la gravedad amigo, pues se calcula en base a la masa y con cuánta fuerza es atraído uno u otro material o fluido, como el agua y el aceite que se posicionan y se separan por densidad, pero sin gravedad, en el espacio no se separan asi que no puede ser eso, como lo explicas? no sabes… por que eres un idiota.",
  estrellas:
    " Las estrellas son el principal argumento de por que la tierra es esférica, ya que en el hemisferio norte se ven unas estrellas y giran en un sentido, y en el sur se ven otras girando en el sentido contrario,incluso en el ecuador pasan en línea recta y este modelo solo funciona en un modelo esférico, en una tierra plana deberíamos ver las mismas estrellas, busca en youtube: “star trails” en México, Argentina, Ecuador o cualquier país. informate antes de lanzar tonterías, no seas idiota y deja de ser un borrego dormido por conspiracionistas.",
  velocidad:
    "Es verdad,el Movimiento de traslación de la tierra lo realiza a una velocidad aproximada de 107.280 kilómetros por hora. Es decir, 30 kilómetros por segundo, suena a que saldrás disparado de la tierra no?...pues no, eso es por que no sabes de inercia, la velocidad que lleva la tierra es constante, sin aceleraciones o frenadas esto es posible, como cuando vas en un avión o un tren a altas velocidades y pones un vasito con agua y no salta por todas partes, pues mientras menos variaciones tenga menos se sentirá, si la tierra impactara con otro planeta si saldríamos despedidos al espacio, otra cosa es que la atmósfera también acompaña, no hay un roce con nada,y para cubrir con la fuerza de centrifugado, hermano, da una vuelta en 24 hs, gira una bola una vuelta en 24 hs y dime qué fuerza hace. anda ya, es estupido que siga dando argumentos cuando el terraplanista no da una mísera prueba de nada.",
  curvatura: `la curvatura de la tierra puede observarse a partir de los 10.000 metros,pero se necesita un gran arco de visión , recién a los 20.000 metros se hace evidente. Un avión comercial suele viajar a 10.000 metros o 12.000 metros de altura, no es como que puedas sacar la cabeza por alguna ventana y verla, pero quizás pagandote un viaje comercial puedas contratar un avión que alcance mayor altura, pero los terraplanistas son ratas que no tienen ni un mango.`,
  agua: `El agua si puede curvarse, pero requiere una fuerza para ello, existen dos ejemplos claros, uno de ellos es acercar un globo cargado con energía estática a un fino chorro de agua y este se curvara, de la misma forma agregando un líquido ferroso se puede magnetizar el líquido y hacer levitar esferas de liquido negro.
  pero al hablar específicamente de la tierra, en cualquier punto de la superficie el agua busca dirigirse al centro de la tierra, y como la tierra es un geoide, se adhiere a ella, aunque en cortas distancias aparente mantener el nivel, en largas distancias lo pierde, es por eso que los barcos desaparecen en el mar y parecen que se hunden, si fuera plana con un telescopio podrás ver la costa de japón desde un edificio alto, y eso seria una estupidez
  `,
};
module.exports = ANSWER_DICT;

/*

Los objetos JSON se conforman por una lista de llaves (keys) y valores

ejemplo: 

const drogas = {
    frula: "rica"
}

para acceder se puede hacer de 2 formas

drogas.frula = "rica"

drogas["frula"] = "rica"

 */
